const CREATE_GAME = "ADD_CHARACTER";
const DELETE_GAME = "DELETE_CHARACTER";
const FILTER = "FILTER";
const ORDER = "ORDER";
const GET_GAMES = "GET_FAVORITES";

export {
    CREATE_GAME,
    DELETE_GAME,
    FILTER,
    ORDER,
    GET_GAMES
}